### ISSUE TITLE
Regeneration auf Seite 1 lässt sich nicht editieren 

### ISSUE THREAD

**Issue by Gorthian** [Gorthian/Roll20_NoReturn_CharacterSheet#75]
Gemeldet über Discord

**Comment by Gorthian** [comment]
Eingeben ist generell möglich.
Allerdings scheint die Beschriftung bzw. das Layout noch nicht optimal zu sein, was vermuten lies, dass hier ein ganzes Eingabefeld fehlt.

**Comment by Gorthian** [comment]
Nach Rücksprache mit Manni und Melder einfach das Wort "Regeneration" um eine Spalte nach rechts schieben.

**Comment by Gorthian** [comment]
Änderungen bei Roll20 eingereicht: [Pull Request](https://github.com/Roll20/roll20-character-sheets/pull/13135)

**Comment by Ardos84** [comment]
In den Regeln zum Steigern und Erlernen von Skills wird empfohlen, rollenspielseitig das zu steigern was man auch genutzt hat oder was man gezielt trainiert. Bei CoC wird es ähnlich gehandhabt, der Bogen hat ein Kästchen an jeder Fertigkeit, um genutze Fertigkeiten zu markieren. Das könnte im Roll20 einem das Leben einfacher machen.
